<?php
/* @var $block Magento\Framework\View\Element\Template */
$shippingConfigViewModel = $block->getData('shipping_config_view_model');
?>

<div id="free-shipping-banner" data-bind="scope: 'free-shipping-banner'">
    Placeholder text in PHTML |
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "#free-shipping-banner": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>

